---
title: "MS_CNuptake.Rmd"
output: html_document
date: '2022-07-11'
---

### Setup 
```{r setup, include=FALSE}
library(readr) 
library(dplyr)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(Hmisc)
library(missMDA)
library(FactoMineR)
library(plotrix)

# reset validation metrics info
white <- theme(plot.background=element_rect(fill="white", color="white"))
```

### Read data and processing co2 effect

```{r warning=FALSE}
 #read csv
gcme <- read.csv("~/data/gcme/MS_data/plot_data.csv")

#output vcmax prediction under eCO2
gcme_co2 <- subset(gcme,condition=="co2")

#create a new column named Prediction to insert to boxplot
gcme_co2$prediction <- "Prediction"

vcmax_co2_fig <- gcme_co2 %>%
  ggplot( aes(x=ecosystem, y=vcmax)) +
  geom_boxplot(alpha = 0.6, outlier.shape = NA)+
  geom_boxplot(data=gcme_co2,aes(x=prediction,y=pred_vcmax), alpha = 0.6, width = 0.5,color="red",outlier.shape = NA)+
  geom_jitter(size=2,width = 0.3) +
  geom_hline( linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-1,1)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))+
  labs(x="", y=~paste(V[cmax]," response to ",eCO[2])) 

jmax_co2_fig <- gcme_co2 %>%
  ggplot( aes(x=ecosystem, y=jmax)) +
  geom_boxplot(alpha = 0.6,outlier.shape = NA)+
  geom_boxplot(data=gcme_co2,aes(x=prediction,y=pred_jmax), alpha = 0.6, width = 0.5,color="red",outlier.shape = NA) +
  geom_jitter(size=2,width = 0.3) +
  geom_hline( linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-1,1)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))+
  labs(x="", y=~paste(J[max]," response to ",eCO[2])) 

jv_co2_fig <- gcme_co2 %>%
  ggplot( aes(x=ecosystem, y=jmax_vcmax)) +
  geom_boxplot(alpha = 0.6,outlier.shape = NA)+
  geom_boxplot(data=gcme_co2,aes(x=prediction,y=pred_jmax_vcmax), alpha = 0.6, width = 0.5,color="red",outlier.shape = NA) +
  geom_jitter(size=2,width = 0.3) +
  geom_hline( linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-1,1)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))+
  labs(x="", y=~paste(J[max],"/",V[cmax]," response to ",eCO[2])) 

plot_grid(vcmax_co2_fig,jmax_co2_fig,jv_co2_fig,nrow=1,label_size = 15)+theme(plot.background=element_rect(fill="white", color="white"))

ggsave(paste("./output/chap2_co2.jpg",sep=""),width = 15, height = 5)

#also, t-test of prediction vs. observation
t.test(gcme_co2$vcmax,gcme_co2$pred_vcmax) 
t.test(gcme_co2$jmax,gcme_co2$pred_jmax) 
t.test(gcme_co2$jmax_vcmax,gcme_co2$pred_jmax_vcmax) 

```

###Processing light effect

```{r warning=FALSE}
#output vcmax prediction under light
gcme_light <- subset(gcme,condition=="light")
gcme_light$type_name[gcme_light$type_name=="shade_to_sun"] <- "Shade to sun"
gcme_light$type_name[gcme_light$type_name=="low_to_high_light"] <- "Low to high light"

vcmax_light_fig <- gcme_light %>% ggplot( aes(x=type_name, y=vcmax)) +
  geom_jitter(size=2,width = 0.3) +
  geom_boxplot(alpha = 0,outlier.shape = NA)+
  geom_hline( linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-0.5,1)+
  geom_hline(yintercept=mean(gcme_light$pred_vcmax),color="red", size=0.5)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))+
  labs(x="", y=~paste(V[cmax]," response to light")) 

jmax_light_fig <- subset(gcme_light,is.na(jmax)==F) %>% ggplot( aes(x=type_name, y=jmax)) +
  geom_jitter(size=2,width = 0.3) +
  geom_boxplot(alpha = 0,outlier.shape = NA)+
  geom_hline( linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-0.5,1)+
  geom_hline(yintercept=mean(gcme_light$pred_jmax),color="red", size=0.5)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))+
  labs(x="", y=~paste(J[max]," response to light")) 

jv_light_fig <- subset(gcme_light,is.na(jmax_vcmax)==F) %>% ggplot( aes(x=type_name, y=jmax_vcmax)) +
  geom_jitter(size=2,width = 0.3) +
  geom_boxplot(alpha = 0,outlier.shape = NA)+
  geom_hline( linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-0.5,1)+
  geom_hline(yintercept=mean(gcme_light$pred_jmax_vcmax),color="red", size=0.5)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))+
  labs(x="", y=~paste(J[max],"/",V[cmax]," response to light")) 

plot_grid(vcmax_light_fig,jmax_light_fig,jv_light_fig,nrow=1,label_size = 15)+theme(plot.background=element_rect(fill="white", color="white"))

ggsave(paste("./output/chap2_light.jpg",sep=""),width = 15, height = 5)

#also, t-test of prediction vs. observation
t.test(gcme_light$vcmax,gcme_light$pred_vcmax) 
t.test(gcme_light$jmax,gcme_light$pred_jmax) 
t.test(gcme_light$jmax_vcmax,gcme_light$pred_jmax_vcmax) 

```


###Processing warming effect

```{r warning=FALSE}
#output vcmax25 prediction under warming
gcme_warming <- subset(gcme,condition=="warming")
#create a new type name for below figure
gcme_warming$prediction <- "Prediction"
gcme_warming$observation <- "Observation"

w1 <- gcme_warming %>%
  ggplot( aes(x=observation, y=vcmax)) +
  geom_jitter(size=2,color="black",width = 0.3) +
  geom_boxplot(alpha = 0,outlier.shape = NA)+
  geom_jitter(aes(x=prediction, y=pred_vcmax),size=2,color="red",width = 0.3) +
  geom_boxplot(aes(x=prediction, y=pred_vcmax),color="red",alpha = 0.6,outlier.shape = NA)+
  geom_hline(  linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-0.15,0.05)+
  labs(x=" ", y=~paste(V[cmax25]," response to warming")) +
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))

w2 <- gcme_warming %>%
  ggplot( aes(x=observation, y=jmax)) +
  geom_jitter(size=2,color="black",width = 0.3) +
  geom_boxplot(alpha = 0,outlier.shape = NA)+
  geom_jitter(aes(x=prediction, y=pred_jmax),size=2,color="red",width = 0.3) +
  geom_boxplot(aes(x=prediction, y=pred_jmax),color="red",alpha = 0.6,outlier.shape = NA)+
  geom_hline(  linetype = 'dotted',yintercept=0.0, size=0.5)+ ylim(-0.15,0.05)+
  labs(x=" ", y=~paste(J[max25]," response to warming")) +
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))

w3 <- gcme_warming %>%
  ggplot( aes(x=observation, y=jmax_vcmax)) +
  geom_jitter(size=2,color="black",width = 0.3) +
  geom_boxplot(alpha = 0,outlier.shape = NA)+
  geom_jitter(aes(x=prediction, y=pred_jmax_vcmax),size=2,color="red",width = 0.3) +
  geom_boxplot(aes(x=prediction, y=pred_jmax_vcmax),color="red",alpha = 0.6,outlier.shape = NA)+
  geom_hline( linetype = 'dotted', yintercept=0.0, size=0.5)+ ylim(-0.15,0.05)+
  labs(x=" ", y=~paste(J[max25],"/",V[cmax25],," response to warming")) +
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))

plot_grid(w1,w2,w3,nrow=1,label_size = 15)+theme(plot.background=element_rect(fill="white", color="white"))

ggsave(paste("./output/chap2_warming.jpg",sep=""),width = 15, height = 5)


#also, t-test of prediction vs. observation
t.test(gcme_warming$vcmax,gcme_warming$pred_vcmax) 
t.test(gcme_warming$jmax,gcme_warming$pred_jmax) 
t.test(gcme_warming$jmax_vcmax,gcme_warming$pred_jmax_vcmax) 

```

###Processing N fertilization effect

```{r warning=FALSE}
#N fertilization effect on eCO2-vcmax
gcme_nfer <-subset(gcme,type_name=="highN"|type_name=="lowN"|type_name=="No_fertilization"|type_name=="Fertilization")

#7 sites are low vs. high N; 7 sites are without vs. with N. Needs to divide them in colors
gcme_nfer %>% group_by(type_name)  %>% summarise(number = n())

#creat box name
gcme_nfer$type_box[gcme_nfer$type_name=="highN"|gcme_nfer$type_name=="Fertilization"] <- "High nitrogen"
gcme_nfer$type_box[gcme_nfer$type_name=="lowN"|gcme_nfer$type_name=="No_fertilization"] <- "Low nitrogen"

#type_1 high N
a1 <- subset(gcme_nfer,condition=="highN")[,c("exp","vcmax","jmax","jmax_vcmax","condition")]
#type1 low N
a2 <- subset(gcme_nfer,condition=="lowN")[,c("exp","vcmax","jmax","jmax_vcmax","condition")]

#type 2 with N
a3 <- subset(gcme_nfer,condition=="Fertilization")[,c("exp","vcmax","jmax","jmax_vcmax","condition")]
#type 2 without N
a4 <- subset(gcme_nfer,condition=="co2")[,c("exp","vcmax","jmax","jmax_vcmax","condition")]

#combine
df1 <- rbind(a1,a3)
df2 <- rbind(a2,a4)
names(df2) <- c("exp_low","vcmax_low","jmax_low","jmax_vcmax_low","condition_low")

df3 <- as.data.frame(cbind(df1,df2))

df3$ratio_v <- df3$vcmax-df3$vcmax_low
df3$ratio_j <- df3$jmax-df3$jmax_low
df3$ratio_jv <- df3$jmax_vcmax-df3$jmax_vcmax_low
df3$type_box <- "High - low"

f1 <- gcme_nfer %>%
  ggplot( aes(x=type_box, y=vcmax)) +
  geom_boxplot(alpha=0.5,width = 0.7, outlier.shape = NA)+
  geom_jitter(data=subset(gcme_nfer,type_name=="Fertilization"|type_name=="No_fertilization"),aes(x=type_box, y=vcmax),size=2,color="black",width = 0.3)+
  geom_jitter(data=subset(gcme_nfer,type_name=="highN"|type_name=="lowN"),aes(x=type_box, y=vcmax),size=2,color="blue",width = 0.3)+
  geom_hline(  linetype = 'dotted',yintercept=0.0, size=0.5)+ 
  labs(x="", y=~paste(V[cmax]," response to eCO2")) +
  geom_boxplot(data=df3,aes(x=type_box,y=ratio_v),alpha=0.5,width = 0.7, outlier.shape = NA)+
  geom_jitter(data=subset(df3,condition=="Fertilization"),aes(x=type_box, y=ratio_v),size=2,color="black",width = 0.3)+
  geom_jitter(data=subset(df3,condition=="highN"),aes(x=type_box, y=ratio_v),size=2,color="blue",width = 0.3)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))

f2 <- gcme_nfer %>%
  ggplot( aes(x=type_box, y=jmax)) +
  geom_boxplot(alpha=0.5,width = 0.7, outlier.shape = NA)+
  geom_jitter(data=subset(gcme_nfer,type_name=="Fertilization"|type_name=="No_fertilization"),aes(x=type_box, y=jmax),size=2,color="black",width = 0.3)+
  geom_jitter(data=subset(gcme_nfer,type_name=="highN"|type_name=="lowN"),aes(x=type_box, y=jmax),size=2,color="blue",width = 0.3)+
  geom_hline( linetype = 'dotted', yintercept=0.0, size=0.5)+
  labs(x="", y=~paste(J[max]," response to eCO2")) +
  geom_boxplot(data=df3,aes(x=type_box,y=ratio_j),alpha=0.5,width = 0.7, outlier.shape = NA)+
  geom_jitter(data=subset(df3,condition=="Fertilization"),aes(x=type_box, y=ratio_j),size=2,color="black",width = 0.3)+
  geom_jitter(data=subset(df3,condition=="highN"),aes(x=type_box, y=ratio_j),size=2,color="blue",width = 0.3)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))

f3 <- gcme_nfer %>%
  ggplot( aes(x=type_box, y=jmax_vcmax)) +
  geom_boxplot(alpha=0.5,width = 0.7, outlier.shape = NA)+
  geom_jitter(data=subset(gcme_nfer,type_name=="Fertilization"|type_name=="No_fertilization"),aes(x=type_box, y=jmax_vcmax),size=2,color="black",width = 0.3)+
  geom_jitter(data=subset(gcme_nfer,type_name=="highN"|type_name=="lowN"),aes(x=type_box, y=jmax_vcmax),size=2,color="blue",width = 0.3)+
  geom_hline( linetype = 'dotted', yintercept=0.0, size=0.5)+
  labs(x="", y=~paste(J[max],"/",V[cmax]," response to eCO2")) +
  geom_boxplot(data=df3,aes(x=type_box,y=ratio_jv),alpha=0.5,width = 0.7, outlier.shape = NA)+
  geom_jitter(data=subset(df3,condition=="Fertilization"),aes(x=type_box, y=ratio_jv),size=2,color="black",width = 0.3)+
  geom_jitter(data=subset(df3,condition=="highN"),aes(x=type_box, y=ratio_jv),size=2,color="blue",width = 0.3)+
  theme_classic()+coord_flip()+theme(axis.text=element_text(size=12))

plot_grid(f1,f2,f3,nrow=1,label_size = 15)+theme(plot.background=element_rect(fill="white", color="white"))

ggsave(paste("./output/chap2_fertilization.jpg",sep=""),width = 15, height = 8)

#anova test about whether N fertilization will shift vcmax
summary(aov(vcmax ~ type_box, data = gcme_nfer))
summary(aov(jmax ~ type_box, data = gcme_nfer))
summary(aov(jmax_vcmax ~ type_box, data = gcme_nfer))
```

###Processing meta-analysis (co2 effect on vcmax, jmax, anpp..)

```{r warning=FALSE}

#now, meta-analysis of eCO2 responses 
#only keep co2 + fertilization (where only evaluate co2 effect) plots 
gcme_meta <- subset(gcme,condition=="co2"|condition=="Fertilization"|
                      condition=="highN"|condition=="lowN")

#make points labelled well
gcme_meta$type_name[gcme_meta$condition=="highN"] <- "N-fertilization"
gcme_meta$type_name[gcme_meta$condition=="lowN"] <- "N-fertilization"
gcme_meta$type_name[gcme_meta$condition=="Fertilization"] <- "N-fertilization"
gcme_meta$type_name[gcme_meta$condition=="co2"] <- "others"
gcme_meta$type_name[gcme_meta$ecm_type=="Nfix"] <- "N-fixing"

gcme_meta %>% group_by(type_name)  %>% summarise(number = n())

t1 <- ggplot(gcme_meta,aes_string(x="jmax", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+
  stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste(J[max]))

t1a <- ggplot(gcme_meta,aes_string(x="vcmax", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste(V[cmax]))

t2 <- ggplot(gcme_meta,aes_string(x="nmass", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste(N[mass]))

t3 <- ggplot(gcme_meta,aes_string(x="narea", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste(N[area]))

t4 <- ggplot(gcme_meta,aes_string(x="LMA", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste(LMA))

p1 <- ggplot(gcme_meta,aes_string(x="nmass", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste(N[mass]))

p2 <- ggplot(gcme_meta,aes_string(x="narea", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste(N[area]))

p3 <- ggplot(gcme_meta,aes_string(x="LMA", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste(LMA))

#now - for bi-variate relationship
b1 <- ggplot(gcme_meta,aes_string(x="anpp", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=F,linetype = "dashed")+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste(ANPP))

b2 <- ggplot(gcme_meta,aes_string(x="bnpp", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste(BNPP))

b3 <- ggplot(gcme_meta,aes_string(x="root_shoot_ratio", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste(Root/Shoot))

b4 <- ggplot(gcme_meta,aes_string(x="lai", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste("LAI"))

b5 <- ggplot(gcme_meta,aes_string(x="soil_mineral_N", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(V[cmax]))+labs(x=~paste("Soil inorganic N"))

c1 <- ggplot(gcme_meta,aes_string(x="anpp", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste(ANPP))

c2 <- ggplot(gcme_meta,aes_string(x="bnpp", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste(BNPP))

c3 <- ggplot(gcme_meta,aes_string(x="root_shoot_ratio", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+geom_smooth(color="black",method="lm",se=F,linetype = "dashed")+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste(Root/Shoot))

c4 <- ggplot(gcme_meta,aes_string(x="lai", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste("LAI"))

c5 <- ggplot(gcme_meta,aes_string(x="soil_mineral_N", y="jmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(y=~paste(J[max]))+labs(x=~paste("Soil inorganic N"))

#check p-value of leaf traits and output those figures with p < 0.05
gcme_meta_metrics <- gcme_meta[,c("vcmax","jmax","LMA","narea","nmass",
                                  "bnpp","root_shoot_ratio","soil_mineral_N",
                                  "anpp","lai")]
res2 <- rcorr(as.matrix(gcme_meta_metrics))

leaf_pvalue <- as.data.frame(res2$P[,c("narea","LMA","nmass")])
leaf_pvalue[leaf_pvalue<0.05] <- "yes"
leaf_pvalue

#additionally plot Narea vs. Nmass,  narea vs. anpp, LMA vs. root/shoot, LMA vs LAI, Nmass vs. bnpp

d1 <- ggplot(gcme_meta,aes_string(x="nmass", y="narea")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+
  geom_point(aes(color=type_name),size=3)+
  stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(x=~paste(N[mass]))+labs(y=~paste(N[area]))

d2 <- ggplot(gcme_meta,aes_string(x="LMA", y="narea")) +geom_hline(yintercept=0)+
  geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+
  stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+xlim(-0.1,0.7)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(x=~paste("LMA"))+labs(y=~paste(N[area]))

d3 <- ggplot(gcme_meta,aes_string(x="root_shoot_ratio", y="LMA")) +geom_hline(yintercept=0)+
  geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+
  stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(x=~paste("Root / shoot"))+labs(y=~paste(LMA))

d5 <- ggplot(gcme_meta,aes_string(x="bnpp", y="nmass")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+
  geom_smooth(color="black",method="lm",se=T)+
  theme(axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"),legend.position="none")+
  labs(x=~paste("BNPP"))+labs(y=~paste(N[mass]))


final1_legend <- ggplot(gcme_meta,aes_string(x="soil_mineral_N", y="vcmax")) +geom_hline(yintercept=0)+geom_vline(xintercept=0)+geom_point(aes(color=type_name),size=3)+stat_cor(label.y.npc="top", label.x.npc = "left",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),size=7)+geom_smooth(color="black",method="lm",se=F)+theme(text = element_text(size=30),axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"))+
  labs(y=~paste(V[cmax]))+labs(x=~paste("Soil inorganic N"))+scale_colour_discrete(" ")

legend_info <- as_ggplot(get_legend(final1_legend))

white <- theme(plot.background=element_rect(fill="white", color="white"))

plot_grid(t1,t2,t3,t4,legend_info,
          t1a,p1,p2,p3,white,
          b1,b2,b3,b4,b5,
          c1,c2,c3,c4,c5,
          d3,d5,white,white,white,
          nrow=5,
          labels = c('(a)','(b)','(c)','(d)',' ',
                     '(e)','(f)','(g)','(h)',' ',
                     '(i)','(j)','(k)','(l)','(m)',
                     '(n)','(o)','(p)','(q)','(r)',
                     '(s)','(t)',' ', ' ' , ' '), label_size = 23)+
  theme(plot.background=element_rect(fill="white", color="white"))
ggsave(paste("./output/chap2_meta.jpg",sep=""),width = 25, height = 25)
 
```

###PCA analysis and some metrics information

```{r warning=FALSE}
#PCA figure
test <- gcme_meta[,c("lai","vcmax","jmax","narea","LMA","nmass","bnpp","anpp","root_shoot_ratio","soil_mineral_N")]
ncomp <- estim_ncpPCA(test)
res.imp <- imputePCA(test, ncp = ncomp$ncp) #filled by pca function

res.pca <- PCA(res.imp$completeObs,axes=c(1,2))
ggsave(paste("./output/pca1.jpg",sep=""),width = 5, height = 5)
res.pca2 <- PCA(res.imp$completeObs,axes=c(3,4))
ggsave(paste("./output/pca2.jpg",sep=""),width = 5, height = 5)

#create a table for values and SE
mean(gcme_meta$vcmax,na.rm=TRUE);std.error(gcme_meta$vcmax)
mean(gcme_meta$jmax,na.rm=TRUE);std.error(gcme_meta$jmax)
mean(gcme_meta$narea,na.rm=TRUE);std.error(gcme_meta$narea)
mean(gcme_meta$LMA,na.rm=TRUE);std.error(gcme_meta$LMA)
mean(gcme_meta$nmass,na.rm=TRUE);std.error(gcme_meta$nmass)
mean(gcme_meta$bnpp,na.rm=TRUE);std.error(gcme_meta$bnpp)
mean(gcme_meta$anpp,na.rm=TRUE);std.error(gcme_meta$anpp)
mean(gcme_meta$root_shoot_ratio,na.rm=TRUE);std.error(gcme_meta$root_shoot_ratio)
mean(gcme_meta$soil_mineral_N,na.rm=TRUE);std.error(gcme_meta$soil_mineral_N)
mean(gcme_meta$lai,na.rm=TRUE);std.error(gcme_meta$lai)

t.test(gcme_meta$vcmax, mu = 0)
t.test(gcme_meta$jmax, mu = 0)
t.test(gcme_meta$narea, mu = 0)
t.test(gcme_meta$LMA, mu = 0)
t.test(gcme_meta$nmass, mu = 0)
t.test(gcme_meta$bnpp, mu = 0)
t.test(gcme_meta$anpp, mu = 0)
t.test(gcme_meta$root_shoot_ratio, mu = 0)
t.test(gcme_meta$soil_mineral_N, mu = 0)
t.test(gcme_meta$lai, mu = 0) 


```

###qq plot

```{r warning=FALSE}

#create a function
qqplot_output <- function(df,y_name,x_name,type_name,lab_title){
  data1 <- na.omit(df[,c(x_name,y_name,type_name)])
  lm_output <- (lm(data1[,c(y_name)]~data1[,c(x_name)]))
  data1$residual <- as.numeric(resid(lm_output))
  
  output_fig <- ggplot(data1)+
    stat_qq(aes(sample = residual,color=type_name),size=3)+
    stat_qq_line(aes(sample = residual))+
    theme(axis.text=element_text(size=20),title=element_text(size=20),
          axis.title=element_text(size=20),legend.position="none")+
    xlab("Theoritical")+ylab("Residuals")+lab_title

  return(output_fig)
}

q1<- qqplot_output(gcme_meta,"vcmax","jmax","type_name",ggtitle(~paste(V[cmax]," vs. ",J[max],sep=" ")))
q2<- qqplot_output(gcme_meta,"vcmax","nmass","type_name",ggtitle(~paste(V[cmax]," vs. ",N[mass],sep=" ")))
q3<- qqplot_output(gcme_meta,"vcmax","narea","type_name",ggtitle(~paste(V[cmax]," vs. ",N[area],sep=" ")))
q4<- qqplot_output(gcme_meta,"vcmax","LMA","type_name",ggtitle(~paste(V[cmax]," vs. ",LMA,sep=" ")))
q5<- qqplot_output(gcme_meta,"jmax","vcmax","type_name",ggtitle(~paste(J[max]," vs. ",V[cmax],sep=" ")))
q6<- qqplot_output(gcme_meta,"jmax","nmass","type_name",ggtitle(~paste(J[max]," vs. ",N[mass],sep=" ")))
q7<- qqplot_output(gcme_meta,"jmax","narea","type_name",ggtitle(~paste(J[max]," vs. ",N[area],sep=" ")))
q8<- qqplot_output(gcme_meta,"jmax","LMA","type_name",ggtitle(~paste(J[max]," vs. ",LMA,sep=" ")))
q9<- qqplot_output(gcme_meta,"vcmax","anpp","type_name",ggtitle(~paste(V[cmax]," vs. ",ANPP,sep=" ")))
q10<- qqplot_output(gcme_meta,"vcmax","bnpp","type_name",ggtitle(~paste(V[cmax]," vs. ",BNPP,sep=" ")))
q11<- qqplot_output(gcme_meta,"vcmax","root_shoot_ratio","type_name",ggtitle(~paste(V[cmax]," vs. ",Root/Shoot,sep=" ")))
q12<- qqplot_output(gcme_meta,"vcmax","lai","type_name",ggtitle(~paste(V[cmax]," vs. ",LAI,sep=" ")))
q13<- qqplot_output(gcme_meta,"vcmax","soil_mineral_N","type_name",ggtitle(~paste(V[cmax]," vs. ","Soil N",sep=" ")))
q14<- qqplot_output(gcme_meta,"jmax","anpp","type_name",ggtitle(~paste(J[max]," vs. ",ANPP,sep=" ")))
q15<- qqplot_output(gcme_meta,"jmax","bnpp","type_name",ggtitle(~paste(J[max]," vs. ",BNPP,sep=" ")))
q16<- qqplot_output(gcme_meta,"jmax","root_shoot_ratio","type_name",ggtitle(~paste(J[max]," vs. ",Root/Shoot,sep=" ")))
q17<- qqplot_output(gcme_meta,"jmax","lai","type_name",ggtitle(~paste(J[max]," vs. ",LAI,sep=" ")))
q18<- qqplot_output(gcme_meta,"jmax","soil_mineral_N","type_name",ggtitle(~paste(J[max]," vs. ","Soil N",sep=" ")))
q19<- qqplot_output(gcme_meta,"LMA","root_shoot_ratio","type_name",ggtitle(~paste(LMA," vs. ",Root/Shoot,sep=" ")))
q20<- qqplot_output(gcme_meta,"LMA","lai","type_name",ggtitle(~paste(LMA," vs. ",LAI,sep=" ")))
q21<- qqplot_output(gcme_meta,"nmass","bnpp","type_name",ggtitle(~paste(N[mass]," vs. ",BNPP,sep=" ")))


#get legend
legend_fig<- ggplot(gcme_meta, aes( x= "jmax", y = "vcmax")) + 
  geom_point(aes(color=type_name),size=2)+
  theme(text = element_text(size=30),axis.text=element_text(size=25),axis.title=element_text(size=25,face="bold"))+scale_colour_discrete(" ")

legend_info <- as_ggplot(get_legend(legend_fig))

white <- theme(plot.background=element_rect(fill="white", color="white"))

plot_grid(q1,q2,q3,q4,legend_info,
          q5,q6,q7,q8,white,
          q9,q10,q11,q12,q13,
          q14,q15,q16,q17,q18,
          q19,q20,q21,white,white,
          nrow=5,
          labels = c('(a)','(b)','(c)','(d)',' ',
                     '(e)','(f)','(g)','(h)',' ',
                     '(i)','(j)','(k)','(l)','(m)',
                     '(n)','(o)','(p)','(q)','(r)',
                     '(s)','(t)','(u)', ' ' , ' '), label_size = 23)+
  theme(plot.background=element_rect(fill="white", color="white"))
ggsave(paste("./output/chap2_meta_qqplot.jpg",sep=""),width = 25, height = 25)

```